ROOT=../../../../

HB_INC_COMPILE=$(TOP)../include -I$(TOP)$(ROOT)include -I$(ROOT)include

C_SOURCES=\
	blowfish.c \

PRG_SOURCES=\
        hfrmtmpl.prg \
	procini.prg \
	procs7.prg \
	procscri.prg \
	scrdebug.prg \

LIBNAME=procmisc

include $(TOP)$(ROOT)config/lib.cf
