HB_INC_COMPILE=$(TOP)../include -I$(TOP)$(ROOT)include
ROOT=../../../
C_SOURCES=\
	commond.c \
	control.c \
	menu_c.c \
	message.c \
	misc.c \
	window.c \
	wprint.c \
	draw.c \
	drawtext.c
	
	
PRG_SOURCES=\
	drawwidg.prg \
	errorsys.prg \
	gtkmain.prg \
	hbrowse.prg \
	hcheck.prg \
	hcombo.prg \
	hcontrol.prg \
	hcwindow.prg \
	hdialog.prg \
	hedit.prg \
	hfrmtmpl.prg \
	hgraph.prg \
	hpanel.prg \
	hprinter.prg \
	hradio.prg \
	htab.prg \
	hsayimg.prg \
	htimer.prg \
	hupdown.prg \
	hwindow.prg \
	hwinprn.prg \
	menu.prg \
   	
	
LIBNAME=hwgtk

C_USR += -mms-bitfields -I"C:/GTK/include/glib-2.0" -I"C:/GTK/lib/glib-2.0/include" -I"C:/GTK/include/gtk-2.0" -I"C:/GTK/lib/gtk-2.0/include" -I"C:/GTK/include/atk-1.0" -I"C:/GTK/include/pango-1.0" -I"C:/GTK/include/libglade-2.0" -I"C:/GTK/include/libxml2" -I"C:/GTK/include"
	
include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
