ROOT=../../../../

HB_INC_COMPILE=$(TOP)../include -I$(TOP)$(ROOT)include -I$(ROOT)include

C_SOURCES=\
	arr2str.c \
	blowfish.c \

PRG_SOURCES=\
	procini.prg \
	procs7.prg \
	procscri.prg \
	scrdebug.prg \

LIBNAME=procmisc

include $(TOP)$(ROOT)config/lib.cf
