
name: checkwindows

on:
  push:
  #schedule:
  # - cron: "15 5 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'hwgui test'
        default: 'checkonly'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Load Source Code
      run: |
         c:
         git clone https://github.com/harbour/core /temp/harbour32 --depth 1
         git clone https://github.com/JoseQuintas/hwgui /temp/hwgui --depth 1

    - name: mingw 7.3
      uses: dawidd6/action-download-artifact@v2
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         md c:\temp\harbour
         md c:\temp\harbour\comp
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\comp

    - name: Build 32 bits
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\comp\mingw32\bin;c:\temp\harbour\bin
      run: |
         c:
         cd c:\temp\harbour32
         mingw32-make clean install
         cd c:\temp\hwgui
         hbmk2 hwgui.hbp -w3
         hbmk2 hbxml.hbp -w3
         hbmk2 procmisc.hbp -w3
         hbmk2 hwgdebug.hbp -w3

    #- name: Build 64 bits
    #  env:
    #     HB_BUILD_STRIP: all
    #     HB_COMPILER: mingw64
    #     HB_INSTALL_PREFIX: c:\temp\harbour
    #     PATH: c:\temp\comp\mingw64\bin;c:\temp\harbour\bin
    #  run: |
    #     c:
    #     cd \temp\harbour32
    #     mingw32-make clean install
    #     cd c:\temp\hwgui
    #     hbmk2 hwgui.hbp
    #     hbmk2 hbxml.hbp
    #     hbmk2 procmisc.hbp
    #     hbmk2 hwgdebug.hbp
